# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63868bbc8cb01ec888ae26b9815e68f734c2838c6f731e93361e9f20d38ff2aa8fd40e1fbe3430b47eb30767aa7e510e00abd44db7c68f484f6092d825e6a217

test:
  secret_key_base: 49170124398a7b2759c103c8d3c5611bf8bd16a37db038a6ce5cb9b89d8e735a1879dfac2319a87663548f713c8eaf433ecae8e2ad250bd1daf4dd2773814486

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
